### ISSUE TITLE
Rails 4 Support

### ISSUE THREAD

**Issue by matt-morris** [iostat/eav_hashes#4]
This gem looks fantastic, but it's dependent on Rails `~> 3.2.7`.  Is there any plan to update it?  

I found a fork which changes the specified dependencies -- https://github.com/fdeschenes/eav_hashes/commit/53df656f96675cf4d401162f5ee12ab35af51057 -- but I'm a bit hesitant.

**Comment by llmora** [comment]
Submitted a PR (https://github.com/iostat/eav_hashes/pull/5) that adds support for Rails4, if you want to test just add this to your Gemfile:

`gem "eav_hashes", github: 'llmora/eav_hashes', branch: 'rails4-support'`

**Comment by iostat** [comment]
I just approved PR #5. Thank you very much llmora!
